### ISSUE TITLE
fix deployment issue

### ISSUE THREAD

**Issue by redhatn16** [redhatn16/portfolio#1]
I am trying to deploy this repository to github.io site.
I've installed gh-pages package.
But it doesn't deploy it.

**Comment by luckydevn16** [comment]
the repository includes react.js project.
are you going to build and deploy it?

**Comment by redhatn16** [comment]
yeah.
can you please help me to deploy it on github.io?

**Comment by redhatn16** [comment]
it's working now.
excellent!
